Add bookings
LeonidBS/java-shareit pull request #2
Opened 2023-06-29 00:54 UTC by LeonidBS

Sprint 14. Iteration 1

2023-06-30 15:45 UTC, ohelly requested changes
Привет! Отличная работа, в целом мне все нравится. Оставил одно небольшое замечание и одну рекомендацию.

2023-06-30 15:45 UTC, ohelly commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
>  @Data
Необходимо исправить: Аннотацию ``@Data`` не рекомендуется использовать над сущностями, тут хорошее объяснение
https://habr.com/ru/companies/haulmont/articles/564682/

Аналогично для всех остальных сущностей

2023-06-30 15:45 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/service/ItemDbService.java
> +    public ItemDbService(ItemRepository itemRepository,
Рекомендация: От конструктора можно избавиться и использовать аннотацию ломбока ``@RequiredArgsConstructor``, а для того, чтобы ломбок смог подтянуть аннотацию ``@Qualifier`` то в его конфиг необходимо добавить следующую строку:
![image](https://github.com/LeonidBS/java-shareit/assets/51891976/42725b94-c7cb-4fa2-8f5f-366d3312ff7b)

И тогда сервис выглядит следующим образом:
![image](https://github.com/LeonidBS/java-shareit/assets/51891976/66bc4eb0-f3e8-49ab-a89f-8cf192187417)

2023-06-30 17:08 UTC, LeonidBS commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
>  @Data
Исправлено. Спасибо!

2023-06-30 17:08 UTC, LeonidBS commented on src/main/java/ru/practicum/shareit/item/service/ItemDbService.java
> +    public ItemDbService(ItemRepository itemRepository,
Исправлено. Спасибо!

2023-06-30 17:09 UTC, LeonidBS commented
Привет, Владислав! Спасибо за проверку и науку!)

2023-07-01 11:20 UTC, ohelly approved these changes
Привет! Все супер, исправлены все замечания. Работу принимаю, можно двигаться дальше!

2023-07-01 16:06 UTC, merged