Add item requests
LeonidBS/java-shareit pull request #3
Opened 2023-07-16 17:13 UTC by LeonidBS

Задание 15. Прошу проверить СР

2023-07-18 20:24 UTC, ohelly requested changes
Привет! Отличная работа, все работает корректно! Оставил пару рекомендаций - их выполнение на твое усмотрение.

2023-07-18 20:24 UTC, ohelly commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestDbService.java
> +        return ItemRequestMapper.INSTANCE.mapToDto(itemRequestRepository.save(itemRequest));
Рекомендация: Мапперы, сгенерированные мапстрактом, можно сделать бинами спринга, чтобы их инжектить
Для этого необходимо указать параметр componentModel
![image](https://github.com/LeonidBS/java-shareit/assets/51891976/6a94a7e6-dcb4-4228-bfc9-273504aa9d24)

И затем просто заинжектить
![image](https://github.com/LeonidBS/java-shareit/assets/51891976/872214f2-22be-4404-8a0c-50cec015073a)

2023-07-18 20:24 UTC, ohelly commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestDbService.java
> +        requestDto.setItems(itemMapper.mapListToItemDto(itemRepository
Рекомендация: Если добавить связь между ItemRequest и Item (ManyToOne), то от лишнего запроса здесь можно будет избавиться

Либо можно доставать сразу все итемы по реквест айди и раскладывать через HashMap(как было в прошлом проекте) - это сократит количество запросов

2023-07-19 20:39 UTC, LeonidBS commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestDbService.java
> +        requestDto.setItems(itemMapper.mapListToItemDto(itemRepository
Исправил связь, которая была , добавил еще одну,  теперь со стороны Item ManyToOne cо стороны ItemRequest OneToMany и добавил поле List<Item> в ItemRequest Entity. В итоге исключил лишний запрос.  Не стал заморачиваться с мапстракатом для ItemRequest , переделал в самописный маппер и добавил конструктор в энтити чтобы не править еще тьму тестов)).

2023-07-19 20:40 UTC, LeonidBS commented
Спасибо за проверку и ценные замечания!

2023-07-20 19:14 UTC, ohelly approved these changes
Привет! Все отлично, работу принимаю. Можно двигаться дальше!

2023-07-21 14:20 UTC, merged